### ISSUE TITLE
Read xml file error,please help.

### ISSUE THREAD

**Issue by lei-xiaoming** [mavrosxristoforos/get-xml-info#31]
Read xml file error,please help.
- xml file
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="1234" version="1.1.1" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:tools="http://schemas.android.com/tools">
</widget>

```

- git action
```
      - name: Get-app-version
        id: getxml
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: 'config.xml'
          xpath: '//widget/@version'
```

- error message
```
Welcome to Get-XML-Version.
File to read: /home/runner/work/test-git-action/test-git-action/config.xml
XPath: //widget/@version
Zero Nodes Action: error
Namespaces: null
File was read successfully. Proceeding to parse DOM.
Found 0 nodes.
Your xpath did not return any nodes.
Error: Your xpath did not return any nodes.
```

**Comment by lei-xiaoming** [comment]
- After adding namespace, it succeeded.
```
      - name: Get-app-version
        id: getxml
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: 'config.xml'
          xpath: '/w:widget/@version'
          namespaces: '{"w": "http://www.w3.org/ns/widgets"}'
```

- result
```
Run mavrosxristoforos/get-xml-info@2.0
Welcome to Get-XML-Version.
File to read: /home/runner/work/test-git-action/test-git-action/config.xml
XPath: /w:widget/@version
Zero Nodes Action: error
Namespaces: {"w": "http://www.w3.org/ns/widgets"}
File was read successfully. Proceeding to parse DOM.
Found 1 nodes.
Output: 1.1.1
```
