### ISSUE TITLE
XPath didnt return any node

### ISSUE THREAD

**Issue by danielferromeral** [mavrosxristoforos/get-xml-info#6]
Hello.

I'm trying to parse a pom.xml to get the version. The pom looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.4.4</version>
    <relativePath/>
  </parent>
  <version>1.3.2</version>
 ........
</project>
```
And the action looks like this:
```yml
 - name: Get XML
        id: xml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: '//project/version'
```
And everytime i get this error:

File was read successfully. Proceeding to parse DOM.
Found 0 nodes.
Error: Your xpath did not return any nodes.

I have tried with //project, //version, //project/version/text(), but all the time I get the same error. Any tips on how to solve it? 

Thanks in advance.
